import { createApp } from 'vue'
import PrimeVue from 'primevue/config'
import ConfirmationService from 'primevue/confirmationservice'
import ToastService from 'primevue/toastservice'
import Tooltip from 'primevue/tooltip'
import Aura from '@primeuix/themes/aura'
import 'primeicons/primeicons.css'
import './styles.css'
import App from './App.vue'

const zhCN = {
  startsWith: '以此开头',
  contains: '包含',
  notContains: '不包含',
  endsWith: '以此结尾',
  equals: '等于',
  notEquals: '不等于',
  noFilter: '无筛选',
  lt: '小于',
  lte: '小于等于',
  gt: '大于',
  gte: '大于等于',
  dateIs: '日期为',
  dateIsNot: '日期不为',
  dateBefore: '日期早于',
  dateAfter: '日期晚于',
  clear: '清除',
  apply: '应用',
  matchAll: '匹配所有条件',
  matchAny: '匹配任一条件',
  addRule: '添加规则',
  removeRule: '移除规则',
  accept: '确定',
  reject: '取消',
  choose: '选择',
  upload: '上传',
  cancel: '取消',
  completed: '完成',
  pending: '待处理',
  fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
  dayNames: [
    '星期日',
    '星期一',
    '星期二',
    '星期三',
    '星期四',
    '星期五',
    '星期六',
  ],
  dayNamesShort: ['周日', '周一', '周二', '周三', '周四', '周五', '周六'],
  dayNamesMin: ['日', '一', '二', '三', '四', '五', '六'],
  monthNames: [
    '一月',
    '二月',
    '三月',
    '四月',
    '五月',
    '六月',
    '七月',
    '八月',
    '九月',
    '十月',
    '十一月',
    '十二月',
  ],
  monthNamesShort: [
    '1月',
    '2月',
    '3月',
    '4月',
    '5月',
    '6月',
    '7月',
    '8月',
    '9月',
    '10月',
    '11月',
    '12月',
  ],
  chooseYear: '选择年份',
  chooseMonth: '选择月份',
  chooseDate: '选择日期',
  prevDecade: '上一个十年',
  nextDecade: '下一个十年',
  prevYear: '上一年',
  nextYear: '下一年',
  prevMonth: '上个月',
  nextMonth: '下个月',
  prevHour: '上一小时',
  nextHour: '下一小时',
  prevMinute: '上一分钟',
  nextMinute: '下一分钟',
  prevSecond: '上一秒',
  nextSecond: '下一秒',
  am: '上午',
  pm: '下午',
  today: '今天',
  weekHeader: '周',
  firstDayOfWeek: 1,
  showMonthAfterYear: true,
  dateFormat: 'yy-mm-dd',
  weak: '弱',
  medium: '中',
  strong: '强',
  passwordPrompt: '请输入密码',
  emptyFilterMessage: '没有符合条件的结果',
  searchMessage: '有 {0} 个结果可用',
  selectionMessage: '已选择 {0} 项',
  emptySelectionMessage: '未选择项目',
  emptySearchMessage: '没有搜索结果',
  emptyMessage: '暂无数据',
  fileChosenMessage: '已选择 {0} 个文件',
  noFileChosenMessage: '未选择文件',
  aria: {
    trueLabel: '是',
    falseLabel: '否',
    nullLabel: '未选择',
    star: '1 星',
    stars: '{star} 星',
    selectAll: '选择全部',
    unselectAll: '取消全选',
    close: '关闭',
    previous: '上一项',
    next: '下一项',
    navigation: '导航',
    scrollTop: '滚动到顶部',
    moveTop: '移到顶部',
    moveUp: '上移',
    moveDown: '下移',
    moveBottom: '移到底部',
    moveToTarget: '移到目标',
    moveToSource: '移到来源',
    moveAllToTarget: '全部移到目标',
    moveAllToSource: '全部移到来源',
    pageLabel: '第 {page} 页',
    firstPageLabel: '第一页',
    lastPageLabel: '最后一页',
    nextPageLabel: '下一页',
    prevPageLabel: '上一页',
    rowsPerPageLabel: '每页行数',
    jumpToPageDropdownLabel: '跳转到页',
    jumpToPageInputLabel: '输入页码',
    selectRow: '选择行',
    unselectRow: '取消选择行',
    expandRow: '展开行',
    collapseRow: '折叠行',
    showFilterMenu: '显示筛选菜单',
    hideFilterMenu: '隐藏筛选菜单',
    filterOperator: '筛选运算符',
    filterConstraint: '筛选约束',
    editRow: '编辑行',
    saveEdit: '保存编辑',
    cancelEdit: '取消编辑',
    listView: '列表视图',
    gridView: '网格视图',
    slide: '幻灯片',
    slideNumber: '第 {slideNumber} 张',
    zoomImage: '缩放图片',
    zoomIn: '放大',
    zoomOut: '缩小',
    rotateRight: '向右旋转',
    rotateLeft: '向左旋转',
    listLabel: '选项列表',
  },
}

const app = createApp(App)

app
  .use(PrimeVue, {
    locale: zhCN,
    theme: {
      preset: Aura,
      options: {
        darkModeSelector: false,
        cssLayer: {
          name: 'primevue',
          order: 'theme, base, primevue',
        },
      },
    },
    ripple: true,
  })
  .use(ConfirmationService)
  .use(ToastService)

app.directive('tooltip', Tooltip)
app.mount('#app')
